### ISSUE TITLE
Filter posts by tag

### ISSUE THREAD

**Issue by bbkr** [perl6/pl6anet.org#10]
Currently for given feed all posts are published on planet.raku.org.
Which sometimes slurps content unrelated to Raku and clutters the page.

My proposal is to add category filter. For example dev.to offers tags in RSS feed as `<category>` XML tags:

```xml
<item>
<title>UTF-8 Byte Order Mark</title>
<dc:creator>Paweł bbkr Pabian</dc:creator>
<pubDate>Mon, 18 Sep 2023 12:04:18 +0000</pubDate>
<link>https://dev.to/bbkr/utf-8-byte-order-mark-1479</link>
<guid>https://dev.to/bbkr/utf-8-byte-order-mark-1479</guid>
<description>
    ...
</description>
<category>unicode</category>
<category>utf</category>
<category>raku</category>     <==== here
</item>
```

So source feed can be defined as:

```yaml
 -  feed: http://dev.to/feed/bbkr
    title: Paweł bbkr Pabian
    web: http://dev.to/bbkr
    tag: raku
```

And only posts on dev.to tagged with `#raku` will be reposted on planet.raku.org.

Related to: https://github.com/Raku/planet.raku.org/pull/9/files
